# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Generate Hydrated Articles

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run article hydration
        run: |
          bash generate_all.sh

      - name: Upload hydrated articles
        uses: actions/upload-artifact@v3
        with:
          name: hydrated-articles
          path: output/hydrated-articles/
